### ISSUE TITLE
Display a form to add a new level 1 vector

### ISSUE THREAD

**Issue by MaybeJustJames** [vibbits/GGW-Elm#10]
The form should appear at the top of the vector catalogue and filter the vector catalogue.

**Comment by kdp-cloud** [comment]
The user should be able to add a new level 1 construct to the database, using the user interface.

**Comment by kdp-cloud** [comment]
After consulting Delphine, we propose that the "Construct Level 1" link in the nav bar would be replaced with a addButton in the catalogueView (similar to adding Level0 and backbone elements). The addButton would then redirect the user to the "ConstructLevel1" page.
